# Generated by Django 3.2.9 on 2021-12-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0003_alter_plant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='facility_code',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together={('latitude', 'longitude')},
        ),
    ]
