# Generated by Django 3.2.9 on 2021-12-11 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0005_alter_energy_generator_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together=set(),
        ),
    ]
