# Generated by Django 3.2.9 on 2021-12-11 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0006_alter_plant_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='plant',
            name='state',
            field=models.CharField(max_length=5),
        ),
    ]
