# Generated by Django 4.0.1 on 2022-01-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0009_auto_20211216_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energy',
            name='generator_id',
        ),
        migrations.AlterField(
            model_name='energy',
            name='generator_anual_net',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True),
        ),
    ]
