# Generated by Django 4.0.1 on 2022-01-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0010_remove_energy_generator_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='generator_anual_net',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
    ]
