# Generated by Django 4.0.1 on 2022-01-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0011_alter_energy_generator_anual_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plant',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=10),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='nameplate_capacity',
            field=models.DecimalField(decimal_places=3, default=None, max_digits=15),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='num_boilers',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='num_generator',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='primary_fuel',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together={('latitude', 'longitude')},
        ),
        migrations.AlterUniqueTogether(
            name='plant_information',
            unique_together={('plant', 'year')},
        ),
    ]
