# Generated by Django 4.0.1 on 2022-01-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0012_alter_plant_latitude_alter_plant_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='generator_anual_net',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='nameplate_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='num_boilers',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='num_generator',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='plant_information',
            name='primary_fuel',
            field=models.CharField(blank=True, default=None, max_length=5, null=True),
        ),
    ]
