# Generated by Django 4.0.1 on 2022-01-15 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0013_alter_energy_generator_anual_net_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='plant',
            unique_together=set(),
        ),
    ]
