# Generated by Django 3.2.9 on 2021-12-11 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('facility_code', models.IntegerField()),
                ('state', models.CharField(max_length=3)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Plant_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_fuel', models.CharField(max_length=5)),
                ('num_generator', models.IntegerField()),
                ('nameplate_capacity', models.DecimalField(decimal_places=3, max_digits=15)),
                ('num_boilers', models.IntegerField()),
                ('year', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizer.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generator_id', models.IntegerField()),
                ('generator_anual_net', models.DecimalField(decimal_places=3, max_digits=15)),
                ('year', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizer.plant')),
            ],
        ),
    ]
