# Generated by Django 3.2.9 on 2021-12-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0002_auto_20211211_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
