# Generated by Django 3.2.9 on 2021-12-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizer', '0004_auto_20211211_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='generator_id',
            field=models.CharField(max_length=10),
        ),
    ]
